---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginxrs
  labels:
    app: nginx
    environment: dev
spec:
  minReadySeconds: 5
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: heema
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: purpose
              value: learning







