---
apiVersion: v1
kind: Pod
metadata: 
  name: nginx-Lables
  labels: 
    app: nginx
    project: application
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
