---
apiVersion: v1
kind: Service
metadata: 
  name: node-port
  labels: 
    purpose: test
spec:
  type: NodePort
  selector:
    app: nginx1
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30345



     
     
    



