---
apiVersion: v1
kind: Pod
metadata: 
  name: alpine-pod
  labels: 
    app: alpine
    purpose: outside_svc
spec:
  containers:
    - name: alpine
      image: alpine
      command: 
        - sleep
        - 1d
