--- 
apiVersion: v1
kind: Pod
metadata:
  name: init-container
  labels: 
    app: nginx
spec:
  initContainers: 
    - name: init1
      image: alpine
      command: 
        - sleep
        - 5s
    - name: init2
      image: alpine
      command: 
        - sleep
        - 5s  
  containers: 
    - name: nginx
      image: nginx      

