--- 
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: jenkins-rs
  labels: 
    purpose: rsdemo
spec:
  minReadySeconds: 3
  replicas: 3
  selector: 
    matchLabels: 
      app: jenkins
      version: v1
  template: 
    metadata: 
      labels: 
        app: jenkins
        version: v1
    spec: 
      containers:
        - name: jenkins
          image: jenkins/jenkins
          ports: 
            - containerPort: 8080
              protocol: TCP
              

          
        

