---
apiVersion: v1
kind: Pod
metadata: 
  name: nginx1
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80

  
---
apiVersion: v1
kind: Pod
metadata: 
  name: nginx2
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80

---
apiVersion: v1
kind: Pod
metadata: 
  name: nginx3
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80

  
      
 

  
      
 