---
apiVersion: v1
kind: Pod
metadata: 
  name: nginx11
  labels: 
    app: nginx
    project: application
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80

  
---
apiVersion: v1
kind: Pod
metadata: 
  name: nginx2
  labels: 
    app: nginx
    project: application
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80

---
apiVersion: v1
kind: Pod
metadata: 
  name: nginx3
  labels: 
    app: jenkins
    version: v1
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80

  
      
 

  
      
 