---
apiVersion: v1
kind: Pod
metadata: 
  name: nginx1
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
    - name: jenkins
      image: jenkins/jenkins:jdk17
      ports:
        - containerPort: 8080
        


          
