---
apiVersion: v1
kind: Pod
metadata: 
  name: nginx1
  labels: 
    app: nginx
    version: v1.1
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
          protocol: TCP
    - name: logagent
      image: alpine
      args:
        - sleep
        - 1d 
              

  
      
 